import os

root_dir = r"c:\Users\soyst\OneDrive\デスクトップ\vegan"

leftovers = {
    'en': {
        '当店のこだわり': 'Our Commitment',
        'オンラインストアはこちら': 'Online Store',
        '含まれているアレルギー食品': 'Allergens Included',
        '大豆を使用しています。': 'Contains Soy',
        '大豆を使用しています': 'Contains Soy',
        'アーモンドを使用しています': 'Contains Almond',
        'りんごを使用しています': 'Contains Apple',
        'やまいもを使用しています': 'Contains Yam',
        '黒ごまを使用しています': 'Contains Black sesame',
        '※こちらの商品は大豆を使用しています。': '*This product contains soy.',
        '大豆': 'Soy',
        'アーモンド': 'Almond',
        '黒ごま': 'Black sesame',
        'やまいも': 'Yam',
        'りんご': 'Apple',
        '価格': 'Price',
        '円': ' yen',
        '（税込）': '(Tax Included)',
        'プレーン': 'Plain',
        '抹茶': 'Matcha',
        'ココア': 'Cocoa',
        '黒ゴマ': 'Black sesame',
        'その他': 'Others',
        'フル': 'Full',
        'ハーフ': 'Half',
        'ワッフル純豆乳ソフトクリーム': 'Waffle & Pure Soy Milk Soft Serve',
        '濃厚豆乳を使ったソフトクリームと、<br>温かいサクもちなワッフルを<br class="pc">組み合わせた商品です。': 'A combination of rich soy milk soft serve<br>and warm, crispy yet chewy waffles.',
        'ワッフルホイップ': 'Waffle Whip',
        '純豆乳を使用したホイップを<br class="pc">ワッフルで包みました。': 'Waffle wrapped around<br class="pc">whip made from pure soy milk.',
        '純豆乳ソフトクリーム': 'Pure Soy Milk Soft Serve',
        'カップ': 'Cup',
        '濃厚豆乳を使ったソフトクリーム。<br class="pc">牛乳以上のクリーミーさを<br class="pc">目指して作りました。': 'Soft serve made with rich soy milk.<br class="pc">Created to be even creamier<br class="pc">than dairy milk.',
        'アフォガート': 'Affogato',
        'こだわりの豆乳ソフトクリームに<br class="pc">エスプレッソをかけて。<br class="pc">食後にぴったりの大人スイーツです。': 'Espresso poured over<br class="pc">our signature soy milk soft serve.<br class="pc">A perfect grown-up dessert.',
        '黒蜜きなこソフトクリーム': 'Brown Sugar Syrup & Kinako Soft Serve',
        '黒蜜ときなこをトッピング。<br class="pc">和スイーツ好きにはたまらない<br class="pc">組み合わせです。': 'Topped with brown sugar syrup and roasted soy flour.<br class="pc">An irresistible combination for<br class="pc">Japanese sweets lovers.',
        '米粉ジェラート': 'Rice Flour Gelato',
        'ベリーミックス': 'Berry Mix',
        '厳選されたストロベリーとラズベリーをふんだんに使用。フレッシュな酸味と甘みが調和し、彩りも鮮やかです。': 'Made with abundant, carefully selected strawberries and raspberries. A perfect harmony of fresh tartness and sweetness, with a vibrant color.',
        'とろけるショコラ': 'Melting Chocolat',
        '深いカカオのコクが魅力の「とろけるショコラ」。ヴィーガンながらも、クリーミーでリッチな口どけを実現。': 'Featuring the deep richness of cacao. Achieves a creamy and rich melt-in-your-mouth texture despite being vegan.',
        'バニラココナッツ': 'Vanilla Coconut',
        '香り高いバニラとまろやかなココナッツミルクを融合。ココナッツの自然な甘さと、バニラのやさしい香りが絶妙にマッチ。トロピカルな風を感じさせます。': 'A fusion of fragrant vanilla and mild coconut milk. The natural sweetness of coconut and gentle aroma of vanilla match perfectly.',
        '爽やかりんご': 'Refreshing Apple',
        'りんごそのものの甘さと爽やかさが楽しめる、軽やかでフルーティーなジェラート。後味もすっきりとしており、大人から子どもまで気に入っていただけること間違いなし。': 'A light and fruity gelato where you can enjoy the natural sweetness and freshness of apples.',
        'ジューシーすぎるもも': 'Too Juicy Peach',
        'たっぷりの桃果汁を贅沢に使用。まるで完熟した桃そのものを食べているかのような味わいをお届けします。': 'Luxuriously uses plenty of peach juice. Tastes just like eating a fully ripe peach.',
        '至高の濃厚抹茶': 'Supreme Rich Matcha',
        '石臼引きの高級抹茶を贅沢に使用。深みのある香りと、豊かな味わいが口いっぱいに広がります。香料や着色料を使わず、抹茶の本格的な風味を堪能できる一品です。': 'Luxuriously uses premium stone-milled matcha. Authentic flavor without artificial flavors or colors.',
        '香ばしいほうじ茶': 'Fragrant Hojicha',
        '香ばしい焙煎の香りが特徴。リラックスしたい、一息つきたい、そんなシーンにぴったりな、大人のための和風デザートです。': 'Characterized by its fragrant roasted aroma. A Japanese dessert for adults perfect for relaxing.',
        'ジューシードラゴンフルーツ': 'Juicy Dragon Fruit',
        '南国フルーツの代表「ドラゴンフルーツ」を使用した、エキゾチックな一品。鮮やかな色合いと爽やかな味わいが特徴で、見た目も味わいも楽しめます。': 'An exotic item using dragon fruit. Features a vibrant color and refreshing taste.',
        'プレーンドーナツ': 'Plain Donuts',
        'プレーンフレイバーの<br class="phonebr">ドーナツに<br class="pcbr">甘酸っぱい<br class="phonebr">クランベリーをトッピング': 'Plain flavored<br class="phonebr">donut<br class="pcbr">topped with<br class="phonebr">sweet and sour cranberries',
        '国産黒ごまを１００％<br class="phonebr">使用した、<br class="pcbr">プチプチとした<br class="phonebr">食感が楽しい和ドーナツ': 'Uses 100% domestic black sesame.<br class="phonebr">A Japanese-style donut<br class="pcbr">with a fun,<br class="phonebr">crunchy texture',
        '香味豊かな石臼引きの抹茶を<br class="phonebr">使用した、<br class="pcbr">香料、着色料不使用の<br class="phonebr">本格派抹茶スイーツ': 'Made with fragrant stone-milled matcha.<br class="phonebr">An authentic matcha sweet<br class="pcbr">made without<br class="phonebr">artificial flavors or colors',
        'もちもちドーナツにきなこを<br class="phonebr">たっぷりかけた、<br class="pcbr">お子様、<br class="phonebr">女性に大人気の和ドーナツ': 'Chewy donut generously coated<br class="phonebr">with roasted soy flour.<br class="pcbr">A very popular Japanese donut<br class="phonebr">among women and children',
        'ベルガモットが香る<br class="phonebr">アールグレイの紅茶を<br class="phonebr">練り込んだ、大人のドーナッツ': 'An adult donut<br class="phonebr">kneaded with Earl Grey tea<br class="phonebr">fragrant with bergamot',
        '子供から大人まで<br class="phonebr">幅広く愛される、<br class="pcbr">ビターな<br class="phonebr">甘さのチョコレートドーナツ': 'Loved by everyone from children to adults,<br class="phonebr">a chocolate donut<br class="pcbr">with a slightly bitter<br class="phonebr">sweetness',
        'グレーズドーナツ': 'Glazed Donuts',
        '温めるとあまおうの香りが<br class="phonebr">いっぱい広がる<br>人気ナンバーワンドーナツ': 'When warmed, the scent of Amaou strawberries<br class="phonebr">spreads fully.<br>Our most popular donut',
        'イタリアBABBI社の<br class="phonebr">100％ピスタチオ<br class="pcbr">ペーストを<br class="phonebr">贅沢に使用': 'Luxuriously uses<br class="phonebr">100% pistachio<br class="pcbr">paste from<br class="phonebr">Italy\'s BABBI',
        'ベルガモット香るアールグレイ<br class="phonebr">生地に<br class="pcbr">有機無農薬レモングレーズを<br class="phonebr">トッピング': 'Earl Grey dough<br class="phonebr">fragrant with bergamot<br class="pcbr">topped with organic,<br class="phonebr">pesticide-free lemon glaze',
        'きなこドーナツにグレーズ<br class="phonebr">ソースをたっぷり。<br class="pcbr">さらに甘さ<br class="phonebr">控えめの小豆をトッピング': 'Kinako donut generously topped with glaze.<br class="phonebr"><br class="pcbr">Further topped with<br class="phonebr">mildly sweet red beans',
        '国産黒ごまをじっくりと<br class="phonebr">皮ごと練り上げた<br>濃厚焙煎黒ごまグレーズソース': 'A rich roasted black sesame glaze source<br class="phonebr">made by carefully kneading<br>domestic black sesame whole with skin',
        'ビターな甘さの自家製クーベル<br class="phonebr">チュールチョコレートを<br class="phonebr">ショコラドーナツにトッピング': 'Homemade couverture chocolate<br class="phonebr">with a bitter sweetness<br class="phonebr">topped on a chocolat donut',
        '香味豊かな八女抹茶ドーナツに、<br>あんこをトッピングした和ドーナツ': 'A Japanese donut with fragrant Yame matcha dough,<br>topped with red bean paste',
        'ケーキドーナツ': 'Cake Donuts',
        'いちごの優しい香りと甘み<br>見た目も可愛いいので、<br class="phonebr">お持たせにもおすすめです！': 'Gentle scent and sweetness of strawberries.<br>It looks cute too,<br class="phonebr">so it is highly recommended as a gift!',
        'ホロ苦い抹茶と、<br class="phonebr">甘い生地がぴったり<br>お子様も食べやすいお味です': 'The slightly bitter matcha and<br class="phonebr">sweet dough are a perfect match.<br>A flavor that is easy for children to eat',
        'チョコ好きさん大満足！<br>とにかく甘いものが食べたいときに<br>お子様も大好きな味': 'Highly satisfying for chocolate lovers!<br>When you just want to eat something sweet.<br>A flavor that children also love',
        'レモンの爽やかな香りと甘さ<br>さっぱりとした甘さを楽しめます': 'Refreshing scent and sweetness of lemon.<br>You can enjoy a refreshing sweetness',
        '上にはチョコチップのトッピング<br>チョコミン党はぜひ！': 'Topped with chocolate chips on top.<br>A must-try for chocolate mint lovers!',
        'ココナッツの優しい香りと甘さが<br>しっとり生地にぴったり<br>コーヒーと一緒に': 'The gentle scent and sweetness of coconut<br>is perfect for the moist dough.<br>Enjoy with coffee',
        'クランベリー': 'Cranberry',
        'きなこ': 'Roasted Soy Flour',
        'アールグレイ': 'Earl Grey',
        'ショコラ': 'Chocolat',
        'あまおうフランボワーズ': 'Amaou Framboise',
        'ピュアピスタチオ': 'Pure Pistachio',
        'レモンアールグレイ': 'Lemon Earl Grey',
        'きなこグレーズ': 'Kinako Glaze',
        '黒ごまグレーズ': 'Black Sesame Glaze',
        'クーベルチョコナッツ': 'Couverture Chocolate Nuts',
        'モリンガあんこ': 'Moringa Red Bean',
        'いちご': 'Strawberry',
        'ダブルチョコ': 'Double Chocolate',
        'レモン': 'Lemon',
        'チョコミント': 'Chocolate Mint',
        'ココナッツ': 'Coconut'
    },
    'ko': {
        '当店のこだわり': '우리의 고집',
        'オンラインストアはこちら': '온라인 스토어',
        '含まれているアレルギー食品': '포함된 알레르기 식품',
        '大豆を使用しています。': '대두 함유',
        '大豆を使用しています': '대두 함유',
        'アーモンドを使用しています': '아몬드 함유',
        'りんごを使用しています': '사과 함유',
        'やまいもを使用しています': '참마 함유',
        '黒ごまを使用しています': '검은깨 함유',
        '※こちらの商品は大豆を使用しています。': '*이 제품은 대두를 포함하고 있습니다.',
        '大豆': '대두',
        'アーモンド': '아몬드',
        '黒ごま': '검은깨',
        'やまいも': '참마',
        'りんご': '사과',
        '価格': '가격',
        '円': '엔',
        '（税込）': '(세금 포함)',
        'プレーン': '플레인',
        '抹茶': '말차',
        'ココア': '코코아',
        '黒ゴマ': '검은깨',
        'その他': '기타',
        'フル': '풀',
        'ハーフ': '하프',
        'ワッフル純豆乳ソフトクリーム': '와플 & 순두유 소프트 아이스크림',
        '濃厚豆乳を使ったソフトクリームと、<br>温かいサクもちなワッフルを<br class="pc">組み合わせた商品です。': '진한 두유를 사용한 소프트 아이스크림과<br>따뜻하고 바삭 쫄깃한 와플의<br class="pc">조합입니다.',
        'ワッフルホイップ': '와플 휩',
        '純豆乳を使用したホイップを<br class="pc">ワッフルで包みました。': '순두유를 사용한 휩을<br class="pc">와플로 감쌌습니다.',
        '純豆乳ソフトクリーム': '순두유 소프트 아이스크림',
        'カップ': '컵',
        '濃厚豆乳を使ったソフトクリーム。<br class="pc">牛乳以上のクリーミーさを<br class="pc">目指して作りました。': '진한 두유를 사용한 소프트 아이스크림.<br class="pc">우유 이상의 크리미함을<br class="pc">목표로 만들었습니다.',
        'アフォガート': '아포가토',
        'こだわりの豆乳ソフトクリームに<br class="pc">エスプレッソをかけて。<br class="pc">食後にぴったりの大人スイーツです。': '특별한 두유 소프트 아이스크림에<br class="pc">에스프레소를 더해.<br class="pc">식후에 어울리는 어른의 디저트입니다.',
        '黒蜜きなこソフトクリーム': '흑밀 콩가루 소프트 아이스크림',
        '黒蜜ときなこをトッピング。<br class="pc">和スイーツ好きにはたまらない<br class="pc">組み合わせです。': '흑밀과 콩가루 토핑.<br class="pc">일본 디저트를 좋아하는 분들께<br class="pc">최고의 조합입니다.',
        '米粉ジェラート': '쌀가루 젤라또',
        'ベリーミックス': '베리 믹스',
        '厳選されたストロベリーとラズベリーをふんだんに使用。フレッシュな酸味と甘みが調和し、彩りも鮮やかです。': '엄선된 딸기와 라즈베리를 듬뿍 사용했습니다. 신선한 산미와 단맛이 조화를 이루며 색상도 선명합니다.',
        'とろけるショコラ': '사르르 쇼콜라',
        '深いカカオのコクが魅力の「とろけるショコラ」。ヴィーガンながらも、クリーミーでリッチな口どけを実現。': '깊은 카카오의 풍미가 매력입니다. 비건이면서도 크리미하고 리치하게 입안에서 녹습니다.',
        'バニラココナッツ': '바닐라 코코넛',
        '香り高いバニラとまろやかなココナッツミルクを融合。ココナッツの自然な甘さと、バニラのやさしい香りが絶妙にマッチ。トロピカルな風を感じさせます。': '향긋한 바닐라와 부드러운 코코넛 밀크의 융합. 열대풍의 맛을 느낄 수 있습니다.',
        '爽やかりんご': '상쾌한 사과',
        'りんごそのものの甘さと爽やかさが楽しめる、軽やかでフルーティーなジェラート。後味もすっきりとしており、大人から子どもまで気に入っていただけること間違いなし。': '사과 본연의 단맛과 상쾌함을 즐길 수 있는 가볍고 프루티한 젤라또.',
        'ジューシーすぎるもも': '너무 쥬시한 복숭아',
        'たっぷりの桃果汁を贅沢に使用。まるで完熟した桃そのものを食べているかのような味わいをお届けします。': '듬뿍 들어간 복숭아 과즙. 마치 완숙된 복숭아를 그대로 먹는 듯한 맛입니다.',
        '至高の濃厚抹茶': '최고의 진한 말차',
        '石臼引きの高級抹茶を贅沢に使用。深みのある香りと、豊かな味わいが口いっぱいに広がります。香料や着色料を使わず、抹茶の本格的な風味を堪能できる一品です。': '고급 맷돌 말차를 아낌없이 사용. 인공 향료나 착색료 없이 진짜 말차의 풍미를 느낄 수 있습니다.',
        '香ばしいほうじ茶': '고소한 호지차',
        '香ばしい焙煎の香りが特徴。リラックスしたい、一息つきたい、そんなシーンにぴったりな、大人のための和風デザートです。': '고소하게 볶은 향이 특징. 휴식하고 싶을 때 딱 맞는 어른들을 위한 일본식 디저트입니다.',
        'ジューシードラゴンフルーツ': '쥬시 드래곤 프루츠',
        '南国フルーツの代表「ドラゴンフルーツ」を使用した、エキゾチックな一品。鮮やかな色合いと爽やかな味わいが特徴で、見た目も味わいも楽しめます。': '이국적인 드래곤 프루츠. 선명한 색감과 상쾌한 맛이 특징입니다.',
        'プレーンドーナツ': '플레인 도넛',
        'プレーンフレイバーの<br class="phonebr">ドーナツに<br class="pcbr">甘酸っぱい<br class="phonebr">クランベリーをトッピング': '플레인 맛의<br class="phonebr">도넛에<br class="pcbr">새콤달콤한<br class="phonebr">크랜베리 토핑',
        '国産黒ごまを１００％<br class="phonebr">使用した、<br class="pcbr">プチプチとした<br class="phonebr">食感が楽しい和ドーナツ': '국산 검은깨를 100%<br class="phonebr">사용한,<br class="pcbr">톡톡 터지는<br class="phonebr">식감이 즐거운 일본식 도넛',
        '香味豊かな石臼引きの抹茶を<br class="phonebr">使用した、<br class="pcbr">香料、着色料不使用の<br class="phonebr">本格派抹茶スイーツ': '향이 풍부한 맷돌 말차를<br class="phonebr">사용한,<br class="pcbr">향료 및 착색료 무첨가의<br class="phonebr">본격 말차 스위츠',
        'もちもちドーナツにきなこを<br class="phonebr">たっぷりかけた、<br class="pcbr">お子様、<br class="phonebr">女性に大人気の和ドーナツ': '쫄깃한 도넛에 콩가루를<br class="phonebr">듬뿍 뿌린,<br class="pcbr">어린이와<br class="phonebr">여성에게 인기 있는 일본식 도넛',
        'ベルガモットが香る<br class="phonebr">アールグレイの紅茶を<br class="phonebr">練り込んだ、大人のドーナッツ': '베르가못 향이 나는<br class="phonebr">얼그레이 홍차를<br class="phonebr">반죽한 어른의 도넛',
        '子供から大人まで<br class="phonebr">幅広く愛される、<br class="pcbr">ビターな<br class="phonebr">甘さのチョコレートドーナツ': '어린이부터 어른까지<br class="phonebr">폭넓게 사랑받는,<br class="pcbr">쌉쌀한<br class="phonebr">단맛의 초콜릿 도넛',
        'グレーズドーナツ': '글레이즈 도넛',
        '温めるとあまおうの香りが<br class="phonebr">いっぱい広がる<br>人気ナンバーワンドーナツ': '따뜻하게 데우면 아마오우 딸기 향이<br class="phonebr">가득 퍼지는<br>인기 넘버원 도넛',
        'イタリアBABBI社の<br class="phonebr">100％ピスタチオ<br class="pcbr">ペーストを<br class="phonebr">贅沢に使用': '이탈리아 BABBI사의<br class="phonebr">100% 피스타치오<br class="pcbr">페이스트를<br class="phonebr">아낌없이 사용',
        'ベルガモット香るアールグレイ<br class="phonebr">生地に<br class="pcbr">有機無農薬レモングレーズを<br class="phonebr">トッピング': '베르가못 향의 얼그레이<br class="phonebr">반죽에<br class="pcbr">유기농 무농약 레몬 글레이즈를<br class="phonebr">토핑',
        'きなこドーナツにグレーズ<br class="phonebr">ソースをたっぷり。<br class="pcbr">さらに甘さ<br class="phonebr">控えめの小豆をトッピング': '콩가루 도넛에 글레이즈<br class="phonebr">소스를 듬뿍.<br class="pcbr">여기에 단맛을<br class="phonebr">줄인 팥을 토핑',
        '国産黒ごまをじっくりと<br class="phonebr">皮ごと練り上げた<br>濃厚焙煎黒ごまグレーズソース': '국산 검은깨를 정성껏<br class="phonebr">껍질째 갈아 만든<br>진한 로스팅 검은깨 글레이즈 소스',
        'ビターな甘さの自家製クーベル<br class="phonebr">チュールチョコレートを<br class="phonebr">ショコラドーナツにトッピング': '쌉쌀한 단맛의 수제 쿠베르<br class="phonebr">튀르 초콜릿을<br class="phonebr">쇼콜라 도넛에 토핑',
        '香味豊かな八女抹茶ドーナツに、<br>あんこをトッピングした和ドーナツ': '향이 풍부한 야메 말차 도넛에,<br>팥을 토핑한 일본식 도넛',
        'ケーキドーナツ': '케이크 도넛',
        'いちごの優しい香りと甘み<br>見た目も可愛いいので、<br class="phonebr">お持たせにもおすすめです！': '딸기의 부드러운 향과 단맛<br>모양도 귀여워서,<br class="phonebr">선물용으로도 추천합니다!',
        'ホロ苦い抹茶と、<br class="phonebr">甘い生地がぴったり<br>お子様も食べやすいお味です': '쌉싸름한 말차와,<br class="phonebr">달콤한 반죽이 찰떡궁합<br>어린이도 먹기 좋은 맛입니다',
        'チョコ好きさん大満足！<br>とにかく甘いものが食べたいときに<br>お子様も大好きな味': '초코 마니아 대만족!<br>어쨌든 단 것이 먹고 싶을 때<br>어린이도 아주 좋아하는 맛',
        'レモンの爽やかな香りと甘さ<br>さっぱりとした甘さを楽しめます': '레몬의 상쾌한 향과 단맛<br>깔끔한 단맛을 즐길 수 있습니다',
        '上にはチョコチップのトッピング<br>チョコミン党はぜひ！': '위에는 초코칩 토핑<br>민트 초코파는 꼭 드셔보세요!',
        'ココナッツの優しい香りと甘さが<br>しっとり生地にぴったり<br>コーヒーと一緒に': '코코넛의 부드러운 향과 단맛이<br>촉촉한 반죽에 딱<br>커피와 함께 즐기세요',
        'クランベリー': '크랜베리',
        'きなこ': '콩가루',
        'アールグレイ': '얼그레이',
        'ショコラ': '쇼콜라',
        'あまおうフランボワーズ': '아마오우 프랑부아즈',
        'ピュアピスタチオ': '퓨어 피스타치오',
        'レモンアールグレイ': '레몬 얼그레이',
        'きなこグレーズ': '콩가루 글레이즈',
        '黒ごまグレーズ': '검은깨 글레이즈',
        'クーベルチョコナッツ': '쿠베르 초코 너츠',
        'モリンガあんこ': '모링가 팥',
        'いちご': '딸기',
        'ダブルチョコ': '더블 초코',
        'レモン': '레몬',
        'チョコミント': '초코 민트',
        'ココナッツ': '코코넛'
    },
    'zh-cn': {
        '当店のこだわり': '我们的承诺',
        'オンラインストアはこちら': '在线商店',
        '含まれているアレルギー食品': '包含的过敏原',
        '大豆を使用しています。': '含大豆',
        '大豆を使用しています': '含大豆',
        'アーモンドを使用しています': '含杏仁',
        'りんごを使用しています': '含苹果',
        'やまいもを使用しています': '含山药',
        '黒ごまを使用しています': '含黑芝麻',
        '※こちらの商品は大豆を使用しています。': '*本产品含大豆。',
        '大豆': '大豆',
        'アーモンド': '杏仁',
        '黒ごま': '黑芝麻',
        'やまいも': '山药',
        'りんご': '苹果',
        '価格': '价格',
        '円': '日元',
        '（税込）': '(含税)',
        'プレーン': '原味',
        '抹茶': '抹茶',
        'ココア': '可可',
        '黒ゴマ': '黑芝麻',
        'その他': '其他',
        'フル': '全尺寸',
        'ハーフ': '半尺寸',
        'ワッフル純豆乳ソフトクリーム': '华夫饼与纯豆奶冰淇淋',
        '濃厚豆乳を使ったソフトクリームと、<br>温かいサクもちなワッフルを<br class="pc">組み合わせた商品です。': '浓郁豆奶冰淇淋与<br>外酥内软温热华夫饼的<br class="pc">完美结合。',
        'ワッフルホイップ': '华夫饼打发奶油',
        '純豆乳を使用したホイップを<br class="pc">ワッフルで包みました。': '用华夫饼包裹<br class="pc">纯豆奶制成的鲜奶油。',
        '純豆乳ソフトクリーム': '纯豆奶软冰淇淋',
        'カップ': '杯装',
        '濃厚豆乳を使ったソフトクリーム。<br class="pc">牛乳以上のクリーミーさを<br class="pc">目指して作りました。': '使用浓郁豆奶的冰淇淋。<br class="pc">旨在打造比牛奶<br class="pc">更绵密的口感。',
        'アフォガート': '阿芙佳朵',
        'こだわりの豆乳ソフトクリームに<br class="pc">エスプレッソをかけて。<br class="pc">食後にぴったりの大人スイーツです。': '在招牌豆奶冰淇淋上<br class="pc">淋上意式浓缩咖啡。<br class="pc">完美的餐后甜点。',
        '黒蜜きなこソフトクリーム': '黑糖黄豆粉软冰淇淋',
        '黒蜜ときなこをトッピング。<br class="pc">和スイーツ好きにはたまらない<br class="pc">組み合わせです。': '加上黑糖浆与黄豆粉。<br class="pc">和式甜点爱好者的<br class="pc">不可抗拒之选。',
        '米粉ジェラート': '米粉意式冰淇淋',
        'ベリーミックス': '混合浆果',
        '厳選されたストロベリーとラズベリーをふんだんに使用。フレッシュな酸味と甘みが調和し、彩りも鮮やかです。': '大量使用精选草莓与覆盆子。新鲜酸甜完美调和，色彩鲜艳。',
        'とろけるショコラ': '融化巧克力',
        '深いカカオのコクが魅力の「とろけるショコラ」。ヴィーガンながらも、クリーミーでリッチな口どけを実現。': '深邃的可可风味。虽然是纯素，却实现了如奶油般丰富的入口即化口感。',
        'バニラココナッツ': '香草椰子',
        '香り高いバニラとまろやかなココナッツミルクを融合。ココナッツの自然な甘さと、バニラのやさしい香りが絶妙にマッチ。トロピカルな風を感じさせます。': '芳香香草与温和椰奶的融合。椰子的自然甜味与香草的温和香气完美匹配。',
        '爽やかりんご': '清爽苹果',
        'りんごそのものの甘さと爽やかさが楽しめる、軽やかでフルーティーなジェラート。後味もすっきりとしており、大人から子どもまで気に入っていただけること間違いなし。': '能享受苹果原本甜味与清爽的轻盈果味冰淇淋。',
        'ジューシーすぎるもも': '超多汁水蜜桃',
        'たっぷりの桃果汁を贅沢に使用。まるで完熟した桃そのものを食べているかのような味わいをお届けします。': '奢侈地使用大量桃汁。仿佛在吃完熟的水蜜桃。',
        '至高の濃厚抹茶': '至高浓郁抹茶',
        '石臼引きの高級抹茶を贅沢に使用。深みのある香りと、豊かな味わいが口いっぱいに広がります。香料や着色料を使わず、抹茶の本格的な風味を堪能できる一品です。': '奢侈地使用高级石磨抹茶。不使用香料或色素，让您享受正宗的抹茶风味。',
        '香ばしいほうじ茶': '香烤焙茶',
        '香ばしい焙煎の香りが特徴。リラックスしたい、一息つきたい、そんなシーンにぴったりな、大人のための和風デザートです。': '以香烤风味为特征。非常适合放松时刻的成人日式甜点。',
        'ジューシードラゴンフルーツ': '多汁火龙果',
        '南国フルーツの代表「ドラゴンフルーツ」を使用した、エキゾチックな一品。鮮やかな色合いと爽やかな味わいが特徴で、見た目も味わいも楽しめます。': '使用火龙果的异国风情之选。色彩鲜艳，口感清爽。',
        'プレーンドーナツ': '原味甜甜圈',
        'プレーンフレイバーの<br class="phonebr">ドーナツに<br class="pcbr">甘酸っぱい<br class="phonebr">クランベリーをトッピング': '原味甜甜圈<br class="phonebr">配上<br class="pcbr">酸甜可口的<br class="phonebr">蔓越莓点缀',
        '国産黒ごまを１００％<br class="phonebr">使用した、<br class="pcbr">プチプチとした<br class="phonebr">食感が楽しい和ドーナツ': '使用100%日本国产黑芝麻，<br class="phonebr">口感<br class="pcbr">层次分明，<br class="phonebr">充满趣味的日式甜甜圈',
        '香味豊かな石臼引きの抹茶を<br class="phonebr">使用した、<br class="pcbr">香料、着色料不使用の<br class="phonebr">本格派抹茶スイーツ': '使用香气四溢的石磨抹茶，<br class="phonebr">不含<br class="pcbr">香料和色素的<br class="phonebr">正宗抹茶甜点',
        'もちもちドーナツにきなこを<br class="phonebr">たっぷりかけた、<br class="pcbr">お子様、<br class="phonebr">女性に大人気の和ドーナツ': '软糯的甜甜圈撒上<br class="phonebr">大量黄豆粉，<br class="pcbr">深受儿童<br class="phonebr">和女性喜爱的日式甜甜圈',
        'ベルガモットが香る<br class="phonebr">アールグレイの紅茶を<br class="phonebr">練り込んだ、大人のドーナッツ': '揉入散发佛手柑香气的<br class="phonebr">伯爵红茶的<br class="phonebr">成熟风味甜甜圈',
        '子供から大人まで<br class="phonebr">幅広く愛される、<br class="pcbr">ビターな<br class="phonebr">甘さのチョコレートドーナツ': '从儿童到成人<br class="phonebr">都广泛喜爱的，<br class="pcbr">带有微苦<br class="phonebr">甜味的巧克力甜甜圈',
        'グレーズドーナツ': '糖霜甜甜圈',
        '温めるとあまおうの香りが<br class="phonebr">いっぱい広がる<br>人気ナンバーワンドーナツ': '加热后甘王草莓的香气<br class="phonebr">会完全散发出来<br>人气第一的甜甜圈',
        'イタリアBABBI社の<br class="phonebr">100％ピスタチオ<br class="pcbr">ペーストを<br class="phonebr">贅沢に使用': '奢侈地使用<br class="phonebr">意大利BABBI公司的<br class="pcbr">100%开心果<br class="phonebr">酱',
        'ベルガモット香るアールグレイ<br class="phonebr">生地に<br class="pcbr">有機無農薬レモングレーズを<br class="phonebr">トッピング': '在散发佛手柑香气的伯爵茶<br class="phonebr">面团上<br class="pcbr">点缀有机无农药柠檬糖霜<br class="phonebr">',
        'きなこドーナツにグレーズ<br class="phonebr">ソースをたっぷり。<br class="pcbr">さらに甘さ<br class="phonebr">控えめの小豆をトッピング': '黄豆粉甜甜圈淋上充足的糖霜<br class="phonebr">。<br class="pcbr">再配上甜度<br class="phonebr">适中的红豆点缀',
        '国産黒ごまをじっくりと<br class="phonebr">皮ごと練り上げた<br>濃厚焙煎黒ごまグレーズソース': '将日本国产黑芝麻带皮<br class="phonebr">精心揉制而成的<br>浓郁烘焙黑芝麻糖霜',
        'ビターな甘さの自家製クーベル<br class="phonebr">チュールチョコレートを<br class="phonebr">ショコラドーナツにトッピング': '将带有微苦甜味的自制调温<br class="phonebr">巧克力<br class="phonebr">点缀在巧克力甜甜圈上',
        '香味豊かな八女抹茶ドーナツに、<br>あんこをトッピングした和ドーナツ': '在香气四溢的八女抹茶甜甜圈上，<br>点缀红豆泥的日式甜甜圈',
        'ケーキドーナツ': '蛋糕甜甜圈',
        'いちごの優しい香りと甘み<br>見た目も可愛いいので、<br class="phonebr">お持たせにもおすすめです！': '草莓柔和的香气和甜味<br>外观也非常可爱，<br class="phonebr">作为伴手礼也很推荐！',
        'ホロ苦い抹茶と、<br class="phonebr">甘い生地がぴったり<br>お子様も食べやすいお味です': '微苦的抹茶与<br class="phonebr">香甜的面团完美契合<br>儿童也很容易接受的口味',
        'チョコ好きさん大満足！<br>とにかく甘いものが食べたいときに<br>お子様も大好きな味': '巧克力爱好者大满足！<br>无论如何想吃甜食的时候<br>儿童也非常喜欢的味道',
        'レモンの爽やかな香りと甘さ<br>さっぱりとした甘さを楽しめます': '柠檬清爽的香气和甜味<br>可以享受清爽的甜度',
        '上にはチョコチップのトッピング<br>チョコミン党はぜひ！': '上面点缀有巧克力片<br>薄荷巧克力爱好者一定要尝试！',
        'ココナッツの優しい香りと甘さが<br>しっとり生地にぴったり<br>コーヒーと一緒に': '椰子柔和的香气和甜味<br>与湿润的面团完美契合<br>适合搭配咖啡',
        'クランベリー': '蔓越莓',
        'きなこ': '黄豆粉',
        'アールグレイ': '伯爵红茶',
        'ショコラ': '巧克力',
        'あまおうフランボワーズ': '甘王覆盆子',
        'ピュアピスタチオ': '纯正开心果',
        'レモンアールグレイ': '柠檬伯爵茶',
        'きなこグレーズ': '黄豆粉糖霜',
        '黒ごまグレーズ': '黑芝麻糖霜',
        'クーベルチョコナッツ': '调温巧克力坚果',
        'モリンガあんこ': '辣木红豆',
        'いちご': '草莓',
        'ダブルチョコ': '双重巧克力',
        'レモン': '柠檬',
        'チョコミント': '薄荷巧克力',
        'ココナッツ': '椰子'
    },
    'zh-tw': {
        '当店のこだわり': '我們的堅持',
        'オンラインストアはこちら': '線上商店',
        '含まれているアレルギー食品': '包含的過敏原',
        '大豆を使用しています。': '含大豆',
        '大豆を使用しています': '含大豆',
        'アーモンドを使用しています': '含杏仁',
        'りんごを使用しています': '含蘋果',
        'やまいもを使用しています': '含山藥',
        '黒ごまを使用しています': '含黑芝麻',
        '※こちらの商品は大豆を使用しています。': '*本產品含大豆。',
        '大豆': '大豆',
        'アーモンド': '杏仁',
        '黒ごま': '黑芝麻',
        'やまいも': '山藥',
        'りんご': '蘋果',
        '価格': '價格',
        '円': '日圓',
        '（税込）': '(含稅)',
        'プレーン': '原味',
        '抹茶': '抹茶',
        'ココア': '可可',
        '黒ゴマ': '黑芝麻',
        'その他': '其他',
        'フル': '全尺寸',
        'ハーフ': '半尺寸',
        'ワッフル純豆乳ソフトクリーム': '華夫餅與純豆奶冰淇淋',
        '濃厚豆乳を使ったソフトクリームと、<br>温かいサクもちなワッフルを<br class="pc">組み合わせた商品です。': '濃郁豆奶冰淇淋與<br>外酥內軟溫熱華夫餅的<br class="pc">完美結合。',
        'ワッフルホイップ': '華夫餅打發奶油',
        '純豆乳を使用したホイップを<br class="pc">ワッフルで包みました。': '用華夫餅包裹<br class="pc">純豆奶製成的鮮奶油。',
        '純豆乳ソフトクリーム': '純豆奶軟冰淇淋',
        'カップ': '杯裝',
        '濃厚豆乳を使ったソフトクリーム。<br class="pc">牛乳以上のクリーミーさを<br class="pc">目指して作りました。': '使用濃郁豆奶的冰淇淋。<br class="pc">旨在打造比牛奶<br class="pc">更綿密的口感。',
        'アフォガート': '阿芙佳朵',
        'こだわりの豆乳ソフトクリームに<br class="pc">エスプレッソをかけて。<br class="pc">食後にぴったりの大人スイーツです。': '在招牌豆奶冰淇淋上<br class="pc">淋上義式濃縮咖啡。<br class="pc">完美的餐後甜點。',
        '黒蜜きなこソフトクリーム': '黑糖黃豆粉軟冰淇淋',
        '黒蜜ときなこをトッピング。<br class="pc">和スイーツ好きにはたまらない<br class="pc">組み合わせです。': '加上黑糖漿與黃豆粉。<br class="pc">和式甜點愛好者的<br class="pc">不可抗拒之選。',
        '米粉ジェラート': '米粉義式冰淇淋',
        'ベリーミックス': '混合漿果',
        '厳選されたストロベリーとラズベリーをふんだんに使用。フレッシュな酸味と甘みが調和し、彩りも鮮やかです。': '大量使用精選草莓與覆盆子。新鮮酸甜完美調和，色彩鮮豔。',
        'とろけるショコラ': '融化巧克力',
        '深いカカオのコクが魅力の「とろけるショコラ」。ヴィーガンながらも、クリーミーでリッチな口どけを実現。': '深邃的可可風味。雖然是純素，卻實現了如奶油般豐富的入口即化口感。',
        'バニラココナッツ': '香草椰子',
        '香り高いバニラとまろやかなココナッツミルクを融合。ココナッツの自然な甘さと、バニラのやさしい香りが絶妙にマッチ。トロピカルな風を感じさせます。': '芳香香草與溫和椰奶的融合。椰子的自然甜味與香草的溫和香氣完美匹配。',
        '爽やかりんご': '清爽蘋果',
        'りんごそのものの甘さと爽やかさが楽しめる、軽やかでフルーティーなジェラート。後味もすっきりとしており、大人から子どもまで気に入っていただけること間違いなし。': '能享受蘋果原本甜味與清爽的輕盈果味冰淇淋。',
        'ジューシーすぎるもも': '超多汁水蜜桃',
        'たっぷりの桃果汁を贅沢に使用。まるで完熟した桃そのものを食べているかのような味わいをお届けします。': '奢侈地使用大量桃汁。彷彿在吃完熟的水蜜桃。',
        '至高の濃厚抹茶': '至高濃郁抹茶',
        '石臼引きの高級抹茶を贅沢に使用。深みのある香りと、豊かな味わいが口いっぱいに広がります。香料や着色料を使わず、抹茶の本格的な風味を堪能できる一品です。': '奢侈地使用高級石磨抹茶。不使用香料或色素，讓您享受正宗的抹茶風味。',
        '香ばしいほうじ茶': '香烤焙茶',
        '香ばしい焙煎の香りが特徴。リラックスしたい、一息つきたい、そんなシーンにぴったりな、大人のための和風デザートです。': '以香烤風味為特徵。非常適合放鬆時刻的成人日式甜點。',
        'ジューシードラゴンフルーツ': '多汁火龍果',
        '南国フルーツの代表「ドラゴンフルーツ」を使用した、エキゾチックな一品。鮮やかな色合いと爽やかな味わいが特徴で、見た目も味わいも楽しめます。': '使用火龍果的異國風情之選。色彩鮮豔，口感清爽。',
        'プレーンドーナツ': '原味甜甜圈',
        'プレーンフレイバーの<br class="phonebr">ドーナツに<br class="pcbr">甘酸っぱい<br class="phonebr">クランベリーをトッピング': '原味甜甜圈<br class="phonebr">配上<br class="pcbr">酸甜可口的<br class="phonebr">蔓越莓點綴',
        '国産黒ごまを１００％<br class="phonebr">使用した、<br class="pcbr">プチプチとした<br class="phonebr">食感が楽しい和ドーナツ': '使用100%日本國產黑芝麻，<br class="phonebr">口感<br class="pcbr">層次分明，<br class="phonebr">充滿趣味的日式甜甜圈',
        '香味豊かな石臼引きの抹茶を<br class="phonebr">使用した、<br class="pcbr">香料、着色料不使用の<br class="phonebr">本格派抹茶スイーツ': '使用香氣四溢的石磨抹茶，<br class="phonebr">不含<br class="pcbr">香料和色素的<br class="phonebr">正宗抹茶甜點',
        'もちもちドーナツにきなこを<br class="phonebr">たっぷりかけた、<br class="pcbr">お子様、<br class="phonebr">女性に大人気の和ドーナツ': '軟糯的甜甜圈撒上<br class="phonebr">大量黃豆粉，<br class="pcbr">深受兒童<br class="phonebr">和女性喜愛的日式甜甜圈',
        'ベルガモットが香る<br class="phonebr">アールグレイの紅茶を<br class="phonebr">練り込んだ、大人のドーナッツ': '揉入散發佛手柑香氣的<br class="phonebr">伯爵紅茶的<br class="phonebr">成熟風味甜甜圈',
        '子供から大人まで<br class="phonebr">幅広く愛される、<br class="pcbr">ビターな<br class="phonebr">甘さのチョコレートドーナツ': '從兒童到成人都<br class="phonebr">廣泛喜愛的，<br class="pcbr">帶有微苦<br class="phonebr">甜味的巧克力甜甜圈',
        'グレーズドーナツ': '糖霜甜甜圈',
        '温めるとあまおうの香りが<br class="phonebr">いっぱい広がる<br>人気ナンバーワンドーナツ': '加熱後甘王草莓的香氣<br class="phonebr">會完全散發出來<br>人氣第一的甜甜圈',
        'イタリアBABBI社の<br class="phonebr">100％ピスタチオ<br class="pcbr">ペーストを<br class="phonebr">贅沢に使用': '奢侈地使用<br class="phonebr">義大利BABBI公司的<br class="pcbr">100%開心果<br class="phonebr">醬',
        'ベルガモット香るアールグレイ<br class="phonebr">生地に<br class="pcbr">有機無農薬レモングレーズを<br class="phonebr">トッピング': '在散發佛手柑香氣的伯爵茶<br class="phonebr">麵團上<br class="pcbr">點綴有機無農藥檸檬糖霜<br class="phonebr">',
        'きなこドーナツにグレーズ<br class="phonebr">ソースをたっぷり。<br class="pcbr">さらに甘さ<br class="phonebr">控えめの小豆をトッピング': '黃豆粉甜甜圈淋上充足的糖霜<br class="phonebr">。<br class="pcbr">再配上甜度<br class="phonebr">適中的紅豆點綴',
        '国産黒ごまをじっくりと<br class="phonebr">皮ごと練り上げた<br>濃厚焙煎黒ごまグレーズソース': '將日本國產黑芝麻帶皮<br class="phonebr">精心揉製而成的<br>濃郁烘焙黑芝麻糖霜',
        'ビターな甘さの自家製クーベル<br class="phonebr">チュールチョコレートを<br class="phonebr">ショコラドーナツにトッピング': '將帶有微苦甜味的自製調溫<br class="phonebr">巧克力<br class="phonebr">點綴在巧克力甜甜圈上',
        '香味豊かな八女抹茶ドーナツに、<br>あんこをトッピングした和ドーナツ': '在香氣四溢的八女抹茶甜甜圈上，<br>點綴紅豆泥的日式甜甜圈',
        'ケーキドーナツ': '蛋糕甜甜圈',
        'いちごの優しい香りと甘み<br>見た目も可愛いいので、<br class="phonebr">お持たせにもおすすめです！': '草莓柔和的香氣和甜味<br>外觀也非常可愛，<br class="phonebr">作為伴手禮也很推薦！',
        'ホロ苦い抹茶と、<br class="phonebr">甘い生地がぴったり<br>お子様も食べやすいお味です': '微苦的抹茶與<br class="phonebr">香甜的麵團完美契合<br>兒童也很容易接受的口味',
        'チョコ好きさん大満足！<br>とにかく甘いものが食べたいときに<br>お子様も大好きな味': '巧克力愛好者大滿足！<br>無論如何想吃甜食的時候<br>兒童也非常喜歡的味道',
        'レモンの爽やかな香りと甘さ<br>さっぱりとした甘さを楽しめます': '檸檬清爽的香氣和甜味<br>可以享受清爽的甜度',
        '上にはチョコチップのトッピング<br>チョコミン党はぜひ！': '上面點綴有巧克力片<br>薄荷巧克力愛好者一定要嘗試！',
        'ココナッツの優しい香りと甘さが<br>しっとり生地にぴったり<br>コーヒーと一緒に': '椰子柔和的香氣和甜味<br>與濕潤的麵團完美契合<br>適合搭配咖啡',
        'クランベリー': '蔓越莓',
        'きなこ': '黃豆粉',
        'アールグレイ': '伯爵紅茶',
        'ショコラ': '巧克力',
        'あまおうフランボワーズ': '甘王覆盆子',
        'ピュアピスタチオ': '純正開心果',
        'レモンアールグレイ': '檸檬伯爵茶',
        'きなこグレーズ': '黃豆粉糖霜',
        '黒ごまグレーズ': '黑芝麻糖霜',
        'クーベルチョコナッツ': '調溫巧克力堅果',
        'モリンガあんこ': '辣木紅豆',
        'いちご': '草莓',
        'ダブルチョコ': '雙重巧克力',
        'レモン': '檸檬',
        'チョコミント': '薄荷巧克力',
        'ココナッツ': '椰子'
    }
}

for lang, translation_dict in leftovers.items():
    lang_dir = os.path.join(root_dir, lang)
    if not os.path.exists(lang_dir):
        continue
    
    for filename in os.listdir(lang_dir):
        if not filename.endswith('.html'):
            continue
            
        filepath = os.path.join(lang_dir, filename)
        with open(filepath, 'r', encoding='utf-8') as f:
            html = f.read()
            
        # Ensure we replace longer strings first to avoid partial matches causing issues
        for jp_text in sorted(translation_dict.keys(), key=len, reverse=True):
            html = html.replace(jp_text, translation_dict[jp_text])
            
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(html)
            
print("Done translating ALL leftovers meticulously!")
